### ISSUE TITLE
Reminder drops user at main screen.

### ISSUE THREAD

**Issue by majiru** [SparkleFartsTechnology/spartan-schedule#3]
The reminder needs to lead to a screen where they can view upcoming assignments

**Comment by twstagg** [comment]
There's probably some "OnClick" thing for notifications, right?

**Comment by majiru** [comment]
Yes I am just setting it here as a reminder that I need to implement it.  I am working on it now.

**Comment by majiru** [comment]
FIxed! Now drops users at a screen which shows due assignments tomorrow.
